SECRET_KEY = 'OvPZRMy1dnF2ValNrJMF7X47qvkQLrUb2RvGTcJVvYKgUZJrRRoY3OZDi4deX8pI56JBKcRx3CeKhnlSswLe1mWETBIAX1NiXp1l'

PROPAGATE_EXCEPTIONS = True

# Database configuration
SQLALCHEMY_DATABASE_URI = 'sqlite:///MCA.sqlite'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SHOW_SQLALCHEMY_LOG_MESSAGES = False

ERROR_404_HELP = False